[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/javascript"
    Content-Security-Policy = "default-src 'self' https://amalgam.onrender.com https://finnhub.io; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10" 