[build]
builder = "NIXPACKS"
buildCommand = "chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar"
restartPolicyType = "ON_FAILURE"

[env]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75" 