[build]
builder = "NIXPACKS"
buildCommand = "chmod +x mvnw && JAVA_HOME=/usr/lib/jvm/java-21-openjdk ./mvnw clean package -DskipTests -X"

[deploy]
startCommand = "java -jar target/*.jar"
restartPolicyType = "ON_FAILURE"

[env]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
NIXPACKS_JDK_VERSION = "21" 