[build]
builder = "NIXPACKS"
buildCommand = "./mvnw clean install -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar"
restartPolicyType = "ON_FAILURE"

[env]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75" 